<?php

$conf = [
    'ignore_deprecated'  => false,
    'developer_user'     => '',
    'developer_pass'     => '',
    'dba_user'           => '',
    'bug_authentication' => [],
    'assets_source_path' => sysconf('APP_PATH') . DS . 'assets',
    'assets_path'        => sysconf('ROOT_PATH') . DS . 'assets',
    'session'            => [
        'type'      => 'file',
        'name'      => 'BBCSD',
        'domain'    => '',
        'expires'   => 120,
        'secure'    => true,
        'memcached' => [
            'address' => '127.0.0.1',
            'port'    => 11211,
        ],
    ],
    'system_error'       => [
        'reported_errors'  => [
            405,
            406,
            408,
            409,
            410,
            413,
            414,
            415,
            416,
            417,
            418,
            422,
            423,
            424,
            425,
            426,
            450,
            499,
            500,
            501,
            502,
            504,
            505,
        ],
        'save_in_database' => true,
        'table_name'       => '_system_errors',
        'db_server'        => 'default',
        'create_table'     => true,
        'hook'             => [
            'default' => false,
        ],
    ],
    'system_internal_methods' => [
        'about' => false,
        'phpinfo' => false,
        'system_errors' => true,
        'test_error' => false,
    ],
];
